port="8080"

[[api]]
    router="/login"
	method=["post"]
	parameter=["account","password"]
	contenttype="application/x-www-form-urlencoded"
	[api.response]
		type="application/x-www-form-urlencoded"
		errorCode=0
		errorMessage="message"
		[api.response.data]
		type="text"
		content=["aaa"]

[[api]]
	router="/account"
	method=["get","post","patch","delete"]
	parameter=["account","password"]
	contenttype="application/json"
	db=true
	[api.response]
		type="application/x-www-form-urlencoded"
		errorCode=0
		errorMessage="adfs"
        [api.response.data]
		type="db"
		content=["account","password","code"]
	
[[api]]
	router="/check"
	[api.response]
		type="application/x-www-form-urlencoded"     
		errorCode=0
		errorMessage="asdf"
		[api.response.data]
		type="hash"
		content=["sha256","keykeykey"]

[db]
	[[db.schema]]
		key="account"
		type="text"
	[[db.schema]]
		key="password"
		type="sha256"	
	[[db.schema]]
		key="code"
		type="text"

