port="8080"

[[api]]
    router="/login"
	method=["post"]
	parameter=["account","password"]
	contenttype="application/x-www-form-urlencoded"
	[api.response]
		type="application/x-www-form-urlencoded"
		errorCode=0
		errorMessage="message"
		[api.response.data]
		type="text"
		content=["aaa"]

[[api]]
	router="/user"
	method=["get","post","patch","delete","put"]
	parameter=["account","password"]
	contenttype="application/json"
	db=true
	[api.response]
		type="application/json"
		errorCode=0
		errorMessage="success"
        [api.response.data]
		type="db"
		content=["account"]
	
[[api]]
	router="/check"
	method=["post"]
	parameter=["account","password"]
	contenttype="application/json"
	db=false
	[api.response]
		type="application/x-www-form-urlencoded"     
		errorCode=0
		errorMessage="success hash"
		[api.response.data]
		type="hash"
		content=["sha256","keykeykey"]

[db]
	[[db.schema]]
		table="user"
		key="account"
		[[db.schema.columns]]
		name="password"
		content=["sha256",""]
		[[db.schema.columns]]
		name="code"
		content=["text"]
		
	[[db.schema]]
		table="auth"
		key="table"

